use crate::core::chess::{board::*, piece::*};

pub const INITIAL_BOARD: Board = Board {
    pieces: [
        PRESENT | ROOK | WHITE, PRESENT | KNIGHT | WHITE, PRESENT | BISHOP | WHITE, PRESENT | QUEEN | WHITE, PRESENT | KING | WHITE, PRESENT | BISHOP | WHITE, PRESENT | KNIGHT | WHITE, PRESENT | ROOK | WHITE,
        PRESENT | PAWN | WHITE, PRESENT | PAWN | WHITE, PRESENT | PAWN | WHITE, PRESENT | PAWN | WHITE, PRESENT | PAWN | WHITE, PRESENT | PAWN | WHITE, PRESENT | PAWN | WHITE, PRESENT | PAWN | WHITE,
        EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
        EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
        EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
        EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
        PRESENT | PAWN | BLACK, PRESENT | PAWN | BLACK, PRESENT | PAWN | BLACK, PRESENT | PAWN | BLACK, PRESENT | PAWN | BLACK, PRESENT | PAWN | BLACK, PRESENT | PAWN | BLACK, PRESENT | PAWN | BLACK,
        PRESENT | ROOK | BLACK, PRESENT | KNIGHT | BLACK, PRESENT | BISHOP | BLACK, PRESENT | QUEEN | BLACK, PRESENT | KING | BLACK, PRESENT | BISHOP | BLACK, PRESENT | KNIGHT | BLACK, PRESENT | ROOK | BLACK,
    ]
};