package internal

var InitialBoard = Board{
	NextTurn: White,
	Pieces: [64]byte{
		Present | Black | Rook,
		Present | Black | Knight,
		Present | Black | Bishop,
		Present | Black | Queen,
		Present | Black | King,
		Present | Black | Bishop,
		Present | Black | Knight,
		Present | Black | Rook,

		Present | Black | Pawn,
		Present | Black | Pawn,
		Present | Black | Pawn,
		Present | Black | Pawn,
		Present | Black | Pawn,
		Present | Black | Pawn,
		Present | Black | Pawn,
		Present | Black | Pawn,

		Empty,
		Empty,
		Empty,
		Empty,
		Empty,
		Empty,
		Empty,
		Empty,

		Empty,
		Empty,
		Empty,
		Empty,
		Empty,
		Empty,
		Empty,
		Empty,

		Empty,
		Empty,
		Empty,
		Empty,
		Empty,
		Empty,
		Empty,
		Empty,

		Empty,
		Empty,
		Empty,
		Empty,
		Empty,
		Empty,
		Empty,
		Empty,

		Present | White | Pawn,
		Present | White | Pawn,
		Present | White | Pawn,
		Present | White | Pawn,
		Present | White | Pawn,
		Present | White | Pawn,
		Present | White | Pawn,
		Present | White | Pawn,

		Present | White | Rook,
		Present | White | Knight,
		Present | White | Bishop,
		Present | White | Queen,
		Present | White | King,
		Present | White | Bishop,
		Present | White | Knight,
		Present | White | Rook,
	},
}

var InitialBoard2 = Board{
	NextTurn: White,
	Pieces: [64]byte{
		Present | Black | Rook,
		Present | Black | Knight,
		Present | Black | Bishop,
		Present | Black | Queen,
		Present | Black | King,
		Present | Black | Bishop,
		Present | Black | Knight,
		Present | Black | Rook,

		Present | Black | Pawn,
		Present | Black | Pawn,
		Present | Black | Pawn,
		Present | Black | Pawn,
		Present | Black | Pawn,
		Present | Black | Pawn,
		Present | Black | Pawn,
		Present | Black | Pawn,

		Empty,
		Empty,
		Empty,
		Empty,
		Empty,
		Empty,
		Empty,
		Empty,

		Empty,
		Empty,
		Empty,
		Empty,
		Empty,
		Empty,
		Empty,
		Empty,

		Empty,
		Empty,
		Empty,
		Empty,
		Empty,
		Empty,
		Empty,
		Empty,

		Empty,
		Empty,
		Empty,
		Empty,
		Empty,
		Empty,
		Empty,
		Empty,

		Present | White | Pawn,
		Present | White | Pawn,
		Present | White | Pawn,
		Present | White | Pawn,
		Present | White | Pawn,
		Present | White | Pawn,
		Present | White | Pawn,
		Present | White | Pawn,

		Present | White | Rook,
		Present | White | Knight,
		Present | White | Bishop,
		Present | White | Queen,
		Present | White | King,
		Present | White | Bishop,
		Present | White | Knight,
		Present | White | Rook,
	},
}
